//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentHubAPI.USI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="USI.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VerifyUSI", ReplyAction="http://tempuri.org/IService/VerifyUSIResponse")]
        System.Collections.Generic.Dictionary<string, string> VerifyUSI(string wsClientUsername, string wsClientPassword, string USI, string firstName, string lastName, System.DateTime dateOfBirth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VerifyUSI", ReplyAction="http://tempuri.org/IService/VerifyUSIResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> VerifyUSIAsync(string wsClientUsername, string wsClientPassword, string USI, string firstName, string lastName, System.DateTime dateOfBirth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUSI", ReplyAction="http://tempuri.org/IService/CreateUSIResponse")]
        System.Collections.Generic.Dictionary<string, string> CreateUSI(string wsClientUsername, string wsClientPassword, string firstName, string lastName, System.DateTime dateOfBirth, string gender, string emailAddress, string phoneNumber, string address, string postCode, string state, string suburbTownCity, string documentType, System.Collections.Generic.Dictionary<string, string> documentKeys);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUSI", ReplyAction="http://tempuri.org/IService/CreateUSIResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> CreateUSIAsync(string wsClientUsername, string wsClientPassword, string firstName, string lastName, System.DateTime dateOfBirth, string gender, string emailAddress, string phoneNumber, string address, string postCode, string state, string suburbTownCity, string documentType, System.Collections.Generic.Dictionary<string, string> documentKeys);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : StudentHubAPI.USI.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<StudentHubAPI.USI.IService>, StudentHubAPI.USI.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, string> VerifyUSI(string wsClientUsername, string wsClientPassword, string USI, string firstName, string lastName, System.DateTime dateOfBirth) {
            return base.Channel.VerifyUSI(wsClientUsername, wsClientPassword, USI, firstName, lastName, dateOfBirth);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> VerifyUSIAsync(string wsClientUsername, string wsClientPassword, string USI, string firstName, string lastName, System.DateTime dateOfBirth) {
            return base.Channel.VerifyUSIAsync(wsClientUsername, wsClientPassword, USI, firstName, lastName, dateOfBirth);
        }
        
        public System.Collections.Generic.Dictionary<string, string> CreateUSI(string wsClientUsername, string wsClientPassword, string firstName, string lastName, System.DateTime dateOfBirth, string gender, string emailAddress, string phoneNumber, string address, string postCode, string state, string suburbTownCity, string documentType, System.Collections.Generic.Dictionary<string, string> documentKeys) {
            return base.Channel.CreateUSI(wsClientUsername, wsClientPassword, firstName, lastName, dateOfBirth, gender, emailAddress, phoneNumber, address, postCode, state, suburbTownCity, documentType, documentKeys);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> CreateUSIAsync(string wsClientUsername, string wsClientPassword, string firstName, string lastName, System.DateTime dateOfBirth, string gender, string emailAddress, string phoneNumber, string address, string postCode, string state, string suburbTownCity, string documentType, System.Collections.Generic.Dictionary<string, string> documentKeys) {
            return base.Channel.CreateUSIAsync(wsClientUsername, wsClientPassword, firstName, lastName, dateOfBirth, gender, emailAddress, phoneNumber, address, postCode, state, suburbTownCity, documentType, documentKeys);
        }
    }
}
